# Write the new ic_launcher_foreground.xml using ASCII-only PowerShell so
# no encoding quirk in the surrounding transport layer can mangle it.

$content = @'
<?xml version="1.0" encoding="utf-8"?>
<!--
  Adaptive-icon foreground for Gochano.

  Drawn inside a 108dp viewport. The safe zone (the area always visible
  on every launcher shape: circle, squircle, teardrop, square) is the
  centred 66dp circle. Anything outside that may be clipped, so the
  foreground artwork is intentionally inset by ~6dp on every side.

  The foreground is the brand mark itself, rendered in pure white
  (#FFFFFFFF) so it reads against the brand-purple background coming
  from @color/ic_launcher_background and recolours correctly on the
  Android 13 themed-icons feature (which tints the background from
  the user's wallpaper palette).

  The brand mark is:
      * a soft rounded-square plate (corner radius ~16dp in the
        108dp viewport), and
      * a chunky stylised "G" centred inside it.

  Vector form is intentional: a vector foreground keeps the APK small
  and renders crisply at any launcher size; the raster master artwork
  in flutter_app/assets/branding/gochano1.png is used for the legacy
  mipmap-*/ic_launcher.png raster fallback (regenerated by
  tool/regen_launcher_icon.py).

  Master artwork: flutter_app/assets/branding/gochano1.png
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">

    <!-- Rounded-square plate that frames the brand mark. Sits just
         inside the 66dp safe zone so the corners never get clipped
         by a square/squircle launcher mask. -->
    <path
        android:fillColor="#FFFFFFFF"
        android:pathData="M28,28 L80,28 A20,20 0 0 1 100,48 L100,60 A20,20 0 0 1 80,80 L28,80 A20,20 0 0 1 8,60 L8,48 A20,20 0 0 1 28,28 Z" />

    <!-- Bold "G" glyph centred inside the plate. The opening on the
         right is closed by a horizontal bar so the letter reads at
         small sizes (18px in the mipmap-mdpi raster). -->
    <path
        android:fillColor="#FF5B3DF5"
        android:pathData="M54,42 C46.27,42 40,48.27 40,56 C40,63.73 46.27,70 54,70 C58.50,70 62.50,68.20 65.30,65.20 L65.30,59 L54,59 L54,63.20 L61,63.20 C59.50,64.70 56.90,65.80 54,65.80 C48.50,65.80 44.20,61.50 44.20,56 C44.20,50.50 48.50,46.20 54,46.20 C56.90,46.20 59.50,47.30 61.50,49.20 L64,46.70 C61.40,43.90 57.80,42 54,42 Z" />
</vector>
'@

# Use UTF-8 WITHOUT BOM, CRLF line endings, to match the existing project style.
$root = (Resolve-Path '..').Path
$path = Join-Path $root 'android/app/src/main/res/drawable/ic_launcher_foreground.xml'
$content = $content -replace "`r?`n", "`r`n"
[System.IO.File]::WriteAllText(
    $path,
    $content,
    [System.Text.UTF8Encoding]::new($false)
)
Write-Host "wrote $path ($((Get-Item $path).Length) bytes, $(((Get-Content $path) | Measure-Object -Line).Lines) lines)"
